package bandersnatch

import (
	"fmt"
	"math/big"
)

// Point_xtw describes points on the p253-subgroup of the Bandersnatch curve in extended twisted Edwards coordinates.
// Extended means that we additionally store T with T = X*Y/Z. Note that Z is never 0 for points in the subgroup, but see code comment about desingularisation.)
// cf. https://iacr.org/archive/asiacrypt2008/53500329/53500329.pdf
type Point_xtw struct {
	x FieldElement
	y FieldElement
	z FieldElement
	t FieldElement
}

/*
	NOTE: Points described by Point_xtw should really been seen as solutions to the set of homogeneous equations

	ax^2 + y^2 = z^2 + dt^2
	x*y = z*t

	with addition law for P3 = P1 + P2 given by:
	X3 = (X1Y2 + Y1X2)(Z1Z2 - dT1T2)
	Y3 = (Y1Y2 - aX1X2)(Z1Z2 + dT1T2)
	T3 = (X1Y2 + Y1X2)(Y1Y2-aX1X2)
	Z3 = (Z1Z2 - dT1T2)(Z1Z2 + dT1T2)

	which we call the extended twisted Edwards model. We treat this as a curve model (like Weierstrass, Montgomery, (twisted) Edwards) rather than a redundant coordinate representaion.

	Clearly, the set of affine solutions corresponds exactly to the set of affine solutions of the usual twisted Edwards equation ax^2 + y^2 = 1+dx^2y^2
	(with z==1, t==x*y), but there are differences in the behaviour at infinity:
	Notably, the twisted Edwards curve has 2+2 points at infinity and the curve is actually singular there:
	Those are double (in the sense that a desingularization results in two points) points at (1:0:0), (0:1:0) each.
	By contrast, the extended twisted Edwards model has no singularities for a != +/-d (over the algebraic closure, to be clear).
	In fact, the additional t coordinate both improves efficiency and is a very convenient desingularization, where things become more clear.
	The (not neccessarily rational) points at infinity (z==0) of this model are in (x:y:t:z) coordinates:
	(0:sqrtz(d):1:0), (0:-sqrt(d):1:0), (sqrt(d/a):0:1:0), (-sqrt(d/a):0:1:0)
	The first two point have order 4 (doubling them gives (0:-1:0:1)), the latter two points have order 2.
	Now, in the case usually considered in the literature, d is a non-square and a is a square.
	Then all these points at infinity are actually not rational and we even get a unified point addition law that works for all rational points.

	In the bandersnatch case, both a and d are non-squares. This means we get two bona-fide rational(!) points at infinity of order 2.
	The addition law above no longer works in all cases. A lengthy analysis (TODO: Make a pdf and write up the proof or find one in literature) shows that the following holds

	Theorem:
	for P,Q rational, the extended Edwards addition law given above for P1 + P2 does not work if and only if P1 - P2 is a (rational, order-2) point at infinity.

	Consequences:
	The addition law works for all points in the subgroup of size 2*p253, generated by the large-prime p253 subgroup and the affine point of order 2.
	If P1,P2 are both contained in a cyclic subgroup generated by Q, then the addition law can only fail in the following cases:
		One of P1,P2 is the neutral element, the other one is equal to Q and is a point at infinity.
		Q has order 2*p253, P1 = alpha * Q, P2 = beta * Q with alpha-beta == p253 mod 2*p253. We can actually ensure that never happens in our exponentiation algorithms.
*/

// example point on the subgroup specified in the bandersnatch paper
var example_generator_x *big.Int = initIntFromString("0x29c132cc2c0b34c5743711777bbe42f32b79c022ad998465e1e71866a252ae18")
var example_generator_y *big.Int = initIntFromString("0x2a6c669eda123e0f157d8b50badcd586358cad81eee464605e3167b6cc974166")
var example_generator_t *big.Int = new(big.Int).Mul(example_generator_x, example_generator_y)
var example_generator_xtw Point_xtw = func() (ret Point_xtw) {
	ret.x.SetInt(example_generator_x)
	ret.y.SetInt(example_generator_y)
	ret.t.SetInt(example_generator_t)
	ret.z.SetOne()
	return
}()

/*
	Basic functions for Point_xtw
*/

// NeutralElement_<foo> denotes the Neutral Element of the Bandersnatch curve.
var (
	NeutralElement_xtw Point_xtw = Point_xtw{x: FieldElementZero, y: FieldElementOne, t: FieldElementZero, z: FieldElementOne}
)

// These are the three points of order 2 that we can represent with extended twisted coordinates. None of these is in the p253-subgroup, of course.
// Although we do not need or use this, note that SqrtDDivA_fe := sqrt(d/a) == sqrt(2) - 1 due to the way the bandersnatch curve was constructed.
var (
	orderTwoPoint_xtw  Point_xtw = Point_xtw{x: FieldElementZero, y: FieldElementMinusOne, t: FieldElementZero, z: FieldElementOne}
	exceptionalPoint_1 Point_xtw = Point_xtw{x: SqrtDDivA_fe, y: bsFieldElement_64_zero, t: FieldElementOne, z: FieldElementZero}
	exceptionalPoint_2 Point_xtw = func() (ret Point_xtw) {
		ret = exceptionalPoint_1
		ret.x.Neg(&ret.x)
		return
	}()
)

// X_affine returns the X coordinate of the given point in affine twisted Edwards coordinates.
func (P *Point_xtw) X_affine() FieldElement {
	P.makeAffine_x()
	return P.x
}

// Y_affine returns the Y coordinate of the given point in affine twisted Edwards coordinates.
func (P *Point_xtw) Y_affine() FieldElement {
	P.makeAffine_x()
	return P.y
}

// T_affine returns the T coordinate (i.e. T=XY) of the given point in affine twisted Edwards coordinates.
func (P *Point_xtw) T_affine() FieldElement {
	P.makeAffine_x()
	return P.t
}

// X_projective returns the X coordinate of the given point P in projective twisted Edwards coordinates.
// Note that calling functions on P other than X_projective(), Y_projective(), Z() might change the representations of P at will,
// so callers must not interleave calling other functions.
func (P *Point_xtw) X_projective() FieldElement {
	return P.x
}

// Y_projective returns the Y coordinate of the given point P in projective twisted Edwards coordinates.
// Note that calling functions on P other than X_projective(), Y_projective(), Z() might change the representations of P at will,
// so callers must not interleave calling other functions.
func (P *Point_xtw) Y_projective() FieldElement {
	return P.y
}

// Z_projective returns the Z coordinate of the given point P in projective twisted Edwards coordinates.
// Note that calling functions on P other than X_projective(), Y_projective(), Z() might change the representations of P at will,
// so callers must not interleave calling other functions.
func (P *Point_xtw) Z_projective() FieldElement {
	return P.z
}

// T_projective returns the T coordinate of the given point P in projective twisted Edwards coordinates (i.e. T = XY/Z).
// Note that calling functions on P other than X_projective(), Y_projective(), Z() might change the representations of P at will,
// so callers must not interleave calling other functions.
func (P *Point_xtw) T_projective() FieldElement {
	return P.t
}

// Q: Should IsAffine and MakeAffine be exported in the first place?
// Note that the names of the function are misleading. NormalizeAffine might be better.
// (In particular, IsAffine might be mistaken for querying whether a point is at infinity or not)

/* In addition, we might consider normalizing to y==1 rather than z==1 */

func (P *Point_xtw) MakeAffine() {
	if !P.IsAffine() {
		P.makeAffine_x()
	}
}

func (p *Point_xtw) IsAffine() bool {
	return p.z.IsOne()
}

// AffineExtended returns a copy of the point in affine extended coordinates.
func (p *Point_xtw) AffineExtended() Point_axtw {
	p.MakeAffine()
	return Point_axtw{x: p.x, y: p.y, t: p.t}
}

func (p *Point_xtw) ExtendedTwistedEdwards() Point_xtw {
	return *p // Note that Go forces the caller to make a copy.
}

// IsNeutralElement checks if the point P is the neutral element of the curve (modulo the identification of P with P+A).
// Use IsNeutralElement_exact if you do not want this identification.
func (P *Point_xtw) IsNeutralElement() bool {

	// NOTE: This asserts that P is in the correct subgroup or that we work modulo the affine order-2 point (x=0, y=-c, t=0, z=c).
	if P.x.IsZero() {
		if P.y.IsZero() {
			// TODO: Handle error: Singular point
			return false
		}
		return true
	}
	return false
}

// IsNeutralElement_exact tests for zero-ness. It does *NOT* identify P with P+A. We only assume that x,y,t,z satisfy the curve equations.
// Returns false for singularity x==y==t==z==0
func (P *Point_xtw) IsNeutralElement_exact() bool {
	// We check this separately, because we want that specific behaviour on singularity.
	if P.z.IsZero() {
		// TODO: Check for singularity and handle errors
		return false
	}
	return P.x.IsZero() && P.t.IsZero() && P.y.IsEqual(&P.z)
}

// SetNeutral sets the Point P to the neutral element of the curve.
func (P *Point_xtw) SetNeutral() {
	*P = NeutralElement_xtw
}

// clearCofactor4 multiplies a point (which need not be in the subgroup) and multiplies it by the cofactor 4 to ensure the result is in the subgroup.
func (p *Point_xtw) clearCofactor4() {
	p.double_tt(p)
	p.double_tt(p)
}

// clearCofactor4 multiplies a point (which need not be in the subgroup) and multiplies it by 2 to ensure the result is in the subgroup. (The cofactor is 4, but the cofactor group is Z/2 x Z/2, so this is sufficient.)
func (p *Point_xtw) clearCofactor2() {
	p.double_tt(p)
}

// IsSingular checks whether the point is singular (x==y==0, indeed most likely x==y==t==z==0). Singular points must never appear if the library is used correctly. They can appear by
// a) performing operations on points that are not in the correct subgroup
// b) zero-initialized points are singular (Go lacks constructors to fix that).
// The reason why we check x==y==0 and do not check t,z is due to what happens if we perform mixed additions.
func (p *Point_xtw) IsSingular() bool {
	return p.x.IsZero() && p.y.IsZero()
}

func (p *Point_xtw) Add(x CurvePointRead, y CurvePointRead) {
	switch x_real := x.(type) {
	case *Point_xtw:
		switch y_real := y.(type) {
		case *Point_xtw:
			p.add_ttt(x_real, y_real)
		default:
			var y_temp Point_xtw
			y_temp.SetFrom(y_real)
			p.add_ttt(x_real, &y_temp)
		}
	default: // for x
		var x_temp Point_xtw
		x_temp.SetFrom(x_real)
		switch y_real := y.(type) {
		case *Point_xtw:
			p.add_ttt(&x_temp, y_real)
		default:
			var y_temp Point_xtw
			y_temp.SetFrom(y_real)
			p.add_ttt(&x_temp, &y_temp)
		}
	}
}

func (p *Point_xtw) Sub(x CurvePointRead, y CurvePointRead) {
	switch x_real := x.(type) {
	case *Point_xtw:
		switch y_real := y.(type) {
		case *Point_xtw:
			p.sub_ttt(x_real, y_real)
		default:
			var y_temp Point_xtw
			y_temp.SetFrom(y_real)
			p.sub_ttt(x_real, &y_temp)
		}
	default: // for x
		var x_temp Point_xtw
		x_temp.SetFrom(x_real)
		switch y_real := y.(type) {
		case *Point_xtw:
			p.sub_ttt(&x_temp, y_real)
		default:
			var y_temp Point_xtw
			y_temp.SetFrom(y_real)
			p.sub_ttt(&x_temp, &y_temp)
		}
	}
}

func (p *Point_xtw) Neg(from CurvePointRead) {
	switch from_real := from.(type) {
	case *Point_xtw:
		p.neg_tt(from_real)
	default:
		p.SetFrom(from_real)
		p.NegEq()
	}
}

func (p *Point_xtw) Endo(from CurvePointRead) {
	switch from_real := from.(type) {
	case *Point_xtw:
		p.computeEndomorphism_tt(from_real)
	case *Point_axtw:
		p.computeEndomorphism_ta(from_real)
	default:
		p.SetFrom(from)
		p.computeEndomorphism_tt(p)
	}
}

// Endo_safe computes the GLV endomorphism and works for all points.
func (output *Point_xtw) Endo_safe(input CurvePointRead) {
	if input.IsSingular() {
		// TODO: Handle error
		*output = Point_xtw{} // NaN-like behaviour.
	} else if input.IsAtInfinity() {
		*output = orderTwoPoint_xtw
	} else {
		output.Endo(input)
	}
}

func (p *Point_xtw) IsAtInfinity() bool {
	if p.z.IsZero() {
		if p.t.IsZero() {
			// TODO: Handle error: p is probably singularity
			return false
		}
		return true
	}
	return false
}

func (p *Point_xtw) IsEqual(other CurvePointRead) bool {
	switch other_real := other.(type) {
	case *Point_xtw:
		return p.is_equal_tt(other_real)
	case *Point_axtw:
		return p.is_equal_ta(other_real)
	default:
		if p.IsSingular() || other.IsSingular() {
			// TODO: Error handling
			return false
		}
		var temp1, temp2 FieldElement
		var temp_fe FieldElement = other_real.Y_projective()
		temp1.Mul(&p.x, &temp_fe)
		temp_fe = other_real.X_projective()
		temp2.Mul(&p.y, &temp_fe)
		return temp1.IsEqual(&temp2)
	}
}

func (p *Point_xtw) IsEqualExact(other CurvePointRead) bool {
	if p.IsSingular() || other.IsSingular() {
		// TODO: Error handling
		return false
	}
	switch other_real := other.(type) {
	case *Point_xtw:
		return p.is_equal_exact_tt(other_real)
	case *Point_axtw:
		return p.is_equal_exact_ta(other_real)
	default:
		other_temp := other.ExtendedTwistedEdwards()
		return p.is_equal_exact_tt(&other_temp)
	}
}

func (p *Point_xtw) EndoEq() {
	p.computeEndomorphism_tt(p)
}

func (p *Point_xtw) NegEq() {
	p.y.NegEq()
	p.t.NegEq()
}

func (p *Point_xtw) AddEq(x CurvePointRead) {
	p.Add(p, x)
}

func (p *Point_xtw) SubEq(x CurvePointRead) {
	p.Sub(p, x)
}

func (p *Point_xtw) SetFrom(input CurvePointRead) {
	switch from_real := input.(type) {
	case *Point_xtw:
		*p = *from_real
	default:
		p.x = from_real.X_projective()
		p.y = from_real.Y_projective()
		p.z = from_real.Z_projective()
		p.t.Mul(&p.x, &p.y)
		p.x.MulEq(&p.z)
		p.y.MulEq(&p.z)
		p.z.SquareEq()
	}
}

// Note: This does NOT verify that the point is in the correct subgroup. Currently prints on failure (as it is only used in testing for now anyway)
func (p *Point_xtw) verify_Point_on_Curve() bool {
	if p.IsSingular() {
		fmt.Println("Singular Point encountered")
		return false
	}
	var u, v FieldElement
	u.Mul(&p.x, &p.y)
	v.Mul(&p.t, &p.z)
	if !u.IsEqual(&v) {
		fmt.Println("Point with inconsistent coordinates encountered")
		return false
	}
	// We now check the main curve equation.
	u.Mul(&p.t, &p.t)
	u.MulEq(&TwistedEdwardsD_fe) // u = d*t^2
	v.Mul(&p.z, &p.z)
	u.AddEq(&v) // u= dt^2 + z^2
	v.Mul(&p.y, &p.y)
	u.SubEq(&v) // u = z^2 + dt^2 - y^2
	v.Mul(&p.x, &p.x)
	v.multiply_by_five()
	u.AddEq(&v) // u = z^2 + dt^2 - y^2 + 5x^2 ==  z^2 + dt^2 - y^2 - ax^2
	if !u.IsZero() {
		fmt.Printf("Point not on curve encountered: x=0x%x y=0x%x z=0x%x t=0x%x", p.x.ToInt(), p.y.ToInt(), p.z.ToInt(), p.t.ToInt())
		return false
	}
	return true
}
